version: '3.8'

# Production overrides for docker-compose.yml
services:
  backend:
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001", "--workers", "4"]
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    restart: always

  mongodb:
    restart: always
    command: mongod --auth