# Backend Deployment for Kubernetes - Artifactory Version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-backend
  namespace: catalyst
  labels:
    app: catalyst-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalyst-backend
  template:
    metadata:
      labels:
        app: catalyst-backend
    spec:
      # Image pull secret for Artifactory
      imagePullSecrets:
      - name: artifactory-secret
      containers:
      - name: backend
        image: artifactory.devtools.syd.c1.macquarie.com:9996/catalyst-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: catalyst-secrets
              key: mongo-url
        - name: DB_NAME
          value: "catalyst_db"
        - name: EMERGENT_LLM_KEY
          valueFrom:
            secretKeyRef:
              name: catalyst-secrets
              key: emergent-llm-key
        - name: DEFAULT_LLM_PROVIDER
          value: "emergent"
        - name: DEFAULT_LLM_MODEL
          value: "claude-3-7-sonnet-20250219"
        - name: CORS_ORIGINS
          value: "*"
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENVIRONMENT
          value: "production"
        - name: MAX_CONCURRENT_TASKS
          value: "10"
        - name: AGENT_TIMEOUT
          value: "600"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: catalyst-backend
  namespace: catalyst
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: catalyst-backend
